updated packages for libhexabus and hexadaemon

diff --git a/openwrt/package/hexadaemon/hexadaemon.init b/openwrt/package/hexadaemon/hexadaemon.init
--- a/openwrt/package/hexadaemon/hexadaemon.init
+++ b/openwrt/package/hexadaemon/hexadaemon.init
@@ -1,37 +1,52 @@
 #!/bin/sh /etc/rc.common
 # Copyright (c) 2013 Stephan Platz
 
-START=99
+START=94
 
-interface=`uci get network.wan.ifname`
+waninterface=`uci get network.wan.ifname`
+laninterface=`uci get network.lan.ifname`
 
 start()
 {
-	ADDR="";
-	for x in `ip -6 a show scope global | sed "s/.*inet6 \([^ \/]*\).*/\1/;tx;d;:x"`;
-		do ADDR="$ADDR-a $x ";
+	LANADDR="";
+	for x in `ip -6 a show scope global "${laninterface}" | sed "s/.*inet6 \([^ \/]*\).*/\1/;tx;d;:x"`;
+		do LANADDR="${LANADDR}-a $x ";
 	done;
-
-	if [ ! -f /etc/cron.d/hexadaemon ]
+	WANADDR="";
+	for x in `ip -6 a show scope global "${waninterface}" | sed "s/.*inet6 \([^ \/]*\).*/\1/;tx;d;:x"`;
+		do WANADDR="${WANADDR}-a $x ";
+	done;
+	ADDR="";
+	if [ -n "${LANADDR}" ]; then
+		INTERFACES="${INTERFACES}-I ${laninterface} ";
+		ADDR="${ADDR}${LANADDR}";
+	fi
+	if [ -n "${WANADDR}" ]; then
+		INTERFACES="${INTERFACES}-I ${waninterface} ";
+		ADDR="${ADDR}${WANADDR}";
+	fi
+	if [ -n "${ADDR}" ] && [ -n "${INTERFACES}" ];
 	then
-		# Configure cron
-		echo -e '*/5 * * * * [ $(ps w | grep -c hexadaemon) -le 1 ] || /etc/init.d/hexadaemon restart' > /etc/cron.d/hexadaemon
-		cat /etc/cron.d/* > /etc/crontabs/root
+		/usr/bin/hexadaemon -i 2 ${INTERFACES} ${ADDR};
+	else
+		echo "Unable to determine addresses and interfaces to use.";
+		exit 1;
 	fi
 
-	if [ "x$interface" != "x" ];
+	if [ ! -f /etc/cron.d/hexadaemon ];
 	then
-		/usr/bin/hexadaemon -i 2 -I ${interface} ${ADDR}
+		echo -e '*/5 * * * * [ $(ps w | grep -c hexadaemon) -le 1 ] && /etc/init.d/hexadaemon restart' > /etc/cron.d/hexadaemon
+		cat /etc/cron.d/* > /etc/crontabs/root
 	fi
 }
 
 stop()
 {
-	if [ -f /etc/cron.d/hexadaemon ]
+	killall hexadaemon
+
+	if [ -f /etc/cron.d/hexadaemon ];
 	then
 		rm /etc/cron.d/hexadaemon
 		cat /etc/cron.d/* > /etc/crontabs/root
 	fi
-
-	killall hexadaemon
 }
